server:
  host: "0.0.0.0"
  port: 8081
  debug: true

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "iraven"
  sslmode: "disable"
  max_connections: 25
  max_idle_connections: 5

api:
  base_url: "http://localhost:8080"
  timeout: 30

auth:
  jwt_secret: "your-jwt-secret-here"
  session_duration: 86400  # 24 hours in seconds

admin:
  default_page_size: 20
  max_page_size: 100
