apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ .Values.name }}-github-webhook
  namespace: {{ .Values.namespace }}
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    {{ .Values.name }}-webhook:
      port: "12000"
      endpoint: "/{{ .Values.webhook }}"
      method: POST
