apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: iraven-admin-sensor
  namespace: {{ .Values.namespace }}
spec:
  dependencies:
    - name: iraven-admin-webhook
      eventSourceName: iraven-admin-github-webhook
      eventName: iraven-admin-webhook

  triggers:
    - template:
        name: iraven-admin-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: iraven-admin-build-deploy-
                namespace: argo
              spec:
                serviceAccountName: workflow-executor
                entrypoint: build-and-deploy
                workflowTemplateRef:
                  name: iraven-admin-build-and-deploy
                arguments:
                  parameters:
                    - name: repository
                      value: ""
                    - name: branch
                      value: "main"
                    - name: docker-tag
                      value: ""
                    - name: app-name
                      value: "iraven-admin"
                    - name: namespace
                      value: "iraven-admin"
          parameters:
            - src:
                dependencyName: iraven-admin-webhook
                dataKey: body.repository
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: iraven-admin-webhook
                dataKey: body.tag
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: iraven-admin-webhook
                dataKey: body.branch
                value: "main"
              dest: spec.arguments.parameters.1.value
