apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  labels:
    {{- include "iraven-admin.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJoYXJib3Iua291c2hhLmRldiI6IHsKICAgICAgInVzZXJuYW1lIjogImFkbWluIiwKICAgICAgInBhc3N3b3JkIjogIktPS09MSSoqIiwKICAgICAgImVtYWlsIjogImtvdXNoYS5naG9kc2l6YWRAZ21haWwuY29tIiwKICAgICAgImF1dGgiOiAiWVdSdGFXNDZTMDlMVDB4Sktpbz0iCiAgICB9CiAgfQp9Cg==
