{{- if and .Values.persistence .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iraven-admin.fullname" . }}-db
  labels:
    {{- include "iraven-admin.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.persistence.storageClass | default "local-path" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "2Gi" }}
{{- end }}
