apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "iraven-admin.fullname" . }}
  labels:
    {{- include "iraven-admin.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "iraven-admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "iraven-admin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "iraven-admin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: DB_HOST
              value: {{ .Values.config.database.host | quote }}
            - name: DB_PORT
              value: {{ .Values.config.database.port | quote }}
            - name: DB_USER
              value: {{ .Values.config.database.username | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "iraven-admin.fullname" . }}-secret
                  key: db-password
            - name: DB_NAME
              value: {{ .Values.config.database.database | quote }}
            - name: DB_SSLMODE
              value: {{ .Values.config.database.sslmode | quote }}
            - name: API_BASE_URL
              value: {{ .Values.config.api.base_url | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "iraven-admin.fullname" . }}-secret
                  key: jwt-secret
            - name: SERVER_HOST
              value: {{ .Values.config.server.host | quote }}
            - name: SERVER_PORT
              value: {{ .Values.config.server.port | quote }}
            - name: DEBUG
              value: {{ .Values.config.debug | quote }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "iraven-admin.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  strategy:
    blueGreen:
      activeService: {{ include "iraven-admin.fullname" . }}-service
      previewService: {{ include "iraven-admin.fullname" . }}-preview-service
      autoPromotionEnabled: {{ .Values.strategy.blueGreen.autoPromotionEnabled }}
      autoPromotionSeconds: {{ .Values.strategy.blueGreen.autoPromotionSeconds }}
      scaleDownDelaySeconds: {{ .Values.strategy.blueGreen.scaleDownDelaySeconds }}
