apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iraven-admin.fullname" . }}-secret
  labels:
    {{- include "iraven-admin.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwt-secret: {{ .Values.config.auth.jwt_secret | b64enc }}
  db-password: {{ .Values.config.database.password | b64enc }}
