apiVersion: v1
kind: Service
metadata:
  name: {{ include "iraven-admin.fullname" . }}-preview-service
  labels:
    {{- include "iraven-admin.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iraven-admin.selectorLabels" . | nindent 4 }}
